FROM spark:3.5.3-java17

COPY extra-jars-1.0.0-jar-with-dependencies.jar $SPARK_HOME/jars/

# For additional dependencies, add them to a custom folder and set spark.jars option accordingly
# COPY additional-deps.jar $SPARK_HOME/extra-jars/

