{{ if .Values.doInstallPrometheusInHook -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-install-prometheus-job
{{ $metaInfo := dict "PartOf" "monitoring" "Component" "install-prometheus" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-install-prometheus-pod
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 6 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-service-account
      containers:
        - name: {{ .Release.Name }}-install-airflow
          image: "alpine/k8s:1.31.3"
          command:
            - "bash"
            - "-c"
            - |
              helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
              helm repo update

              helm upgrade --install {{ .Release.Name }}-prometheus-stack prometheus-community/kube-prometheus-stack \
                --namespace {{ .Release.Namespace }} \
                --values /config/override-values.yaml
          volumeMounts:
            - name: prometheus-config
              mountPath: "/config"
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Release.Name }}-prometheus-configmap
            items:
            - key: "override-values.yaml"
              path: "override-values.yaml"
  backoffLimit: 1
{{ end -}}
