{{ if not .Values.doInstallAirflowInHook -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-install-airflow-job
{{ $metaInfo := dict "PartOf" "airflow" "Component" "install-job" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-install-airflow-pod
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 6 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-service-account
      containers:
        - name: {{ .Release.Name }}-install-airflow
          image: "alpine/k8s:1.31.3"
          command: 
            - "bash"
            - "-c"
            - |
              helm repo add apache-airflow https://airflow.apache.org

              helm upgrade --install {{ .Release.Name }}-airflow apache-airflow/airflow \
                --namespace {{ .Release.Namespace }} \
                --values /config/override-values.yaml
          volumeMounts:
            - name: airflow-config
              mountPath: "/config"
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: airflow-config
          configMap:
            name: {{ .Release.Name }}-airflow-configmap
            items:
            - key: "override-values.yaml"
              path: "override-values.yaml"
  backoffLimit: 1
{{ end -}}
