apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-upload-spark-pod-template-job
{{ $metaInfo := dict "PartOf" "spark" "Component" "upload-spark-pod-template-job" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-upload-spark-pod-template-pod
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 6 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-service-account
      containers:
        - name: {{ .Release.Name }}-upload-spark-pod-template
          image: "minio/mc:RELEASE.2024-11-17T19-35-25Z"
          command: 
            - "bash"
            - "-c"
            - |
              mc alias set minio {{ template "pipelineDemo.computedS3Endpoint" . }} $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
              mc rm --versions --force minio/{{ .Release.Namespace }}/pod-templates/spark-pod-template.yml || echo "No pod template found!"
              mc put /uploads/spark-pod-template.yml minio/{{ .Release.Namespace }}/pod-templates/spark-pod-template.yml && echo "Pod template successfully uploaded"
          volumeMounts:
            - name: spark-pod-template-volume
              mountPath: "/uploads"
              readOnly: true
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio-credentials-secret
                  key: MINIO_ROOT_USER
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio-credentials-secret
                  key: MINIO_ROOT_PASSWORD
      restartPolicy: Never
      volumes:
        - name: spark-pod-template-volume
          configMap:
            name: {{ .Release.Name }}-spark-task-configmap
            items:
            - key: "spark-pod-template.yml"
              path: "spark-pod-template.yml"
  backoffLimit: 1
