custom-value-serviceAccount: &serviceAccount
  serviceAccount:
    name: {{ .Release.Name }}-service-account
    create: false

# images:
#   airflow:
#     repository: maluz/airflow-kube
#     tag: "1.0.0"

config:
  webserver:
    expose_config: "True"

workers:
  <<: *serviceAccount

scheduler:
  <<: *serviceAccount

createUserJob:
  <<: *serviceAccount

migrateDatabaseJob:
  <<: *serviceAccount

apiServer:
  <<: *serviceAccount

webserver:
  <<: *serviceAccount

triggerer:
  <<: *serviceAccount

dagProcessor:
  <<: *serviceAccount

flower:
  <<: *serviceAccount

statsd:
  <<: *serviceAccount

pgbouncer:
  <<: *serviceAccount

redis:
  <<: *serviceAccount

cleanup:
  <<: *serviceAccount

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://repository.v2.moon-cloud.eu/marco-luzzara/ml-pipeline-dags.git
    branch: main
    subPath: ""
    depth: 1
# https://github.com/apache/airflow/blob/main/chart/values.yaml#L2751
# sshKeySecret: airflow-ssh-secret
# extraSecrets:
#   airflow-ssh-secret:
#     data: |
#       gitSshKey: '<base64-converted-ssh-private-key>'
