# https://github.com/apache/airflow/blob/main/chart/values.yaml
custom-value-serviceAccount: &serviceAccount
  serviceAccount:
    name: {{ .Release.Name }}-service-account
    create: false

images:
  airflow:
    repository: maluz/custom-airflow-k8s
    tag: "2.0.0"

config:
  webserver:
    expose_config: "True"

workers:
  <<: *serviceAccount

scheduler:
  <<: *serviceAccount

createUserJob:
  <<: *serviceAccount

migrateDatabaseJob:
  <<: *serviceAccount

apiServer:
  <<: *serviceAccount

webserver:
  <<: *serviceAccount

triggerer:
  <<: *serviceAccount

dagProcessor:
  <<: *serviceAccount

flower:
  <<: *serviceAccount

statsd:
  <<: *serviceAccount

pgbouncer:
  <<: *serviceAccount

redis:
  <<: *serviceAccount

cleanup:
  <<: *serviceAccount

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: ssh://git@repository.v2.moon-cloud.eu:2222/marco-luzzara/ml-pipeline-dags.git
    branch: main
    subPath: ""
    depth: 1
    sshKeySecret: {{ .Release.Name }}-airflow-sshkey-secret
