apiVersion: v1
kind: Pod
metadata:
  labels:
    isSparkPod: "true"
spec:
  containers:
    - name: spark-pod
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials-secret
              key: MINIO_ROOT_USER
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials-secret
              key: MINIO_ROOT_PASSWORD
