{{ if .Values.dockerRegistryRequired | default false -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  .dockerconfigjson: {{ .Values.dockerConfigJsonEncoded }}
type: kubernetes.io/dockerconfigjson
{{ end -}}
