{{ if .Values.dockerRegistryRequired | default false -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
{{ $metaInfo := dict "PartOf" "common" "Component" "docker-secret" "Global" . -}}
{{ include "prin.commonMetadata" $metaInfo | indent 2 }}
data:
  .dockerconfigjson: {{ .Values.dockerConfigJsonEncoded }}
type: kubernetes.io/dockerconfigjson
{{ end -}}
