{{ if not .Values.minioAlreadyAvailable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio-loadbalancer
{{ $metaInfo := dict "PartOf" "minio" "Component" "svc-lb" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
spec:
  ports:
    - port: 9001
      targetPort: console
      name: console
    - port: 9000
      targetPort: api
      name: api
  type: LoadBalancer
  selector:
{{ include "pipelineDemo.commonLabels" ( dict "PartOf" "minio" "Component" "node" "Global" . ) | indent 4 }}
{{ end -}}
