{{ if not .Values.minioAlreadyAvailable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio-svc
{{ $metaInfo := dict "PartOf" "minio" "Component" "svc" "Global" . -}}
{{ include "prin.commonMetadata" $metaInfo | indent 2 }}
spec:
  ports:
    - port: 9000
      targetPort: api
      name: api
  type: ClusterIP
  clusterIP: None
  selector:
{{ include "prin.commonLabels" ( dict "PartOf" "minio" "Component" "node" "Global" . ) | indent 4 }}
{{ end -}}
