apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-service-account
{{ $metaInfo := dict "PartOf" "auth" "Component" "service-account" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
{{ if .Values.dockerRegistryRequired | default false -}}  
imagePullSecrets:
  - name: {{ .Release.Name }}-registry-secret
{{ end -}}