apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-spark-role
{{ $metaInfo := dict "PartOf" "spark" "Component" "auth" "Global" . -}}
{{ include "prin.commonMetadata" $metaInfo | indent 2 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - list
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - services
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - deletecollection
