apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-spark-task-configmap
{{ $metaInfo := dict "PartOf" "spark" "Component" "task-config" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
data:
  spark-defaults.conf: |
    spark.hadoop.fs.s3a.aws.credentials.provider                com.amazonaws.auth.EnvironmentVariableCredentialsProvider
    spark.hadoop.fs.s3a.endpoint                                {{ if .Values.minioAlreadyAvailable }}{{ .Values.s3Endpoint }}{{ else }}{{ printf "%s-minio-svc.%s:9000" .Release.Name .Release.Namespace }}{{ end }}
    spark.hadoop.fs.s3a.path.style.access                       true
    spark.hadoop.fs.s3a.connection.ssl.enabled                  false
    spark.driver.extraJavaOptions                               --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
    spark.executor.extraJavaOptions                             --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
    spark.kubernetes.container.image                            {{ .Values.sparkTaskContainerImage.repo }}:{{ .Values.sparkTaskContainerImage.tag }}
    spark.kubernetes.driver.podTemplateFile                     {{ .Values.sparkTaskPodTemplatePath }}
    spark.kubernetes.executor.podTemplateFile                   {{ .Values.sparkTaskPodTemplatePath }}
    spark.kubernetes.authenticate.driver.serviceAccountName     {{ .Release.Name }}-service-account
    spark.kubernetes.authenticate.executor.serviceAccountName   {{ .Release.Name }}-service-account
    spark.kubernetes.namespace                                  {{ .Release.Namespace }}