apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-spark-role-binding
{{ $metaInfo := dict "PartOf" "spark" "Component" "auth" "Global" . -}}
{{ include "prin.commonMetadata" $metaInfo | indent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-spark-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-spark-service-account