apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-spark-service-account
{{ $metaInfo := dict "PartOf" "spark" "Component" "auth" "Global" . -}}
{{ include "prin.commonMetadata" $metaInfo | indent 2 }}
{{ if .Values.dockerRegistryRequired | default false -}}  
imagePullSecrets:
  - name: {{ .Release.Name }}-registry-secret
{{ end -}}