apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-service-account
  namespace: spark-k8s
  labels:
    app.kubernetes.io/name: spark

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: spark-k8s
  labels:
    app.kubernetes.io/name: spark
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - services
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: spark-k8s
  labels:
    app.kubernetes.io/name: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
  - kind: ServiceAccount
    name: spark-service-account
