apiVersion: v1
kind: Secret
metadata:
  namespace: spark-k8s
  name: minio-credentials
  labels:
    app.kubernetes.io/name: minio
type: Opaque
data:
  # MINIO_ROOT_USER: miniouser
  MINIO_ROOT_USER: bWluaW91c2Vy
  # MINIO_ROOT_PASSWORD: miniopassword
  MINIO_ROOT_PASSWORD: bWluaW9wYXNzd29yZA==

---
apiVersion: v1
kind: Service
metadata:
  name: minio-loadbalancer
  namespace: spark-k8s
  labels:
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - port: 9001
      targetPort: 9001
      name: console
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  namespace: spark-k8s
  name: minio-service
  labels:
    app.kubernetes.io/name: minio
spec:
  ports:
    - port: 9001
      targetPort: 9001
      name: console
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: minio

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: spark-k8s
  name: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  serviceName: minio-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-05-10T01-41-38Z
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9001
              name: console
            - containerPort: 9000
              name: api
          # volumeMounts:
          #   - name: minio-data
          #     mountPath: /data
          envFrom:
            - secretRef:
                name: minio-credentials
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
  # volumeClaimTemplates:
  #   - metadata:
  #       name: minio-data
  #     spec:
  #       accessModes: ["ReadWriteMany"]
  #       storageClassName: "standard"
  #       resources:
  #         requests:
  #           storage: 1Gi
