apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-service-account-token-secret
{{ $metaInfo := dict "PartOf" "auth" "Component" "service-account-token" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-service-account
type: kubernetes.io/service-account-token