{{ if not .Values.minioAlreadyAvailable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio-loadbalancer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - port: 9001
      targetPort: console
      name: console
    - port: 9000
      targetPort: api
      name: api
  type: LoadBalancer
{{ end -}}
