apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ports:
    - port: 9000
      targetPort: api
      name: api
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
