{{ if .Values.doInstallAirflow -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-airflow-configmap
{{ $metaInfo := dict "PartOf" "airflow" "Component" "config" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
data:
  override-values.yaml: |
{{ tpl ( .Files.Get "files/airflow-values-override.yaml" ) . | indent 4 }}
{{ end -}}
