{{ if .Values.doInstallAirflow -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airflow-sshkey-secret
{{ $metaInfo := dict "PartOf" "airflow" "Component" "sshkey" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
type: Opaque
data:
  gitSshKey: {{ .Files.Get "files/id_rsa" | b64enc }}
{{ end -}}
