{{ if .Values.doInstallGrafana -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana
{{ $metaInfo := dict "PartOf" "grafana" "Component" "secret" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
data:
  admin-user: {{ print "admin-user" | b64enc }}
  admin-password: {{ print "admin-password" | b64enc }}
{{ end -}}
