apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-spark-task-configmap
{{ $metaInfo := dict "PartOf" "spark" "Component" "task-config" "Global" . -}}
{{ include "pipelineDemo.commonMetadata" $metaInfo | indent 2 }}
data:
  spark-defaults.conf: |
{{ tpl ( .Files.Get "files/spark-defaults.conf" ) . | indent 4 }}

  spark-pod-template.yml: |
{{ tpl ( .Files.Get "files/spark-pod-template.yml" ) . | indent 4 }}